In [56]:
import numpy as np

In [2]:
[1,2,3]

[1, 2, 3]

In [ ]:
list


In [3]:
arreglo_np = np.array([1,2,3])

In [4]:
type(arreglo_np)

numpy.ndarray

In [6]:
tupla_np = np.array((1,2,3,4))

In [7]:
type(tupla_np)

numpy.ndarray

In [11]:
np.zeros((5,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones((3))

array([1., 1., 1.])

In [16]:
np.empty((0))

array([], dtype=float64)

In [17]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arreglo_impares = np.arange(1,20,2)

In [27]:
arreglo_impares.size

10

In [30]:
np.arange(24).reshape(6,2,2])

SyntaxError: invalid syntax (<ipython-input-30-16b17ccd9ac2>, line 1)

In [33]:
a = np.array([10,10,10])
b = np.array ((5,5,5))

In [34]:
# suma
a+b

array([15, 15, 15])

In [35]:
a % b

array([0, 0, 0], dtype=int32)

In [36]:
a / 2

array([5., 5., 5.])

In [37]:
a - 3

array([7, 7, 7])

In [41]:
arreglo_doce = np.arange(12)

In [42]:
arreglo_doce > 5







array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [46]:
B = np.arange(4,8).reshape((2,2))

B


array([[4, 5],
       [6, 7]])

In [48]:
A*B



NameError: name 'A' is not defined

In [50]:
a.dot(B)

ValueError: shapes (3,) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)

In [51]:
arreglo_tres = np.arrange(3)
arreglo_tres +=2

AttributeError: module 'numpy' has no attribute 'arrange'

In [59]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)