In [1]:
import numpy as np

In [4]:
numeros = np.arange(11)**2

In [5]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [6]:
indices =[2,5,7]

In [7]:
numeros[indices]

array([ 4, 25, 49], dtype=int32)

In [8]:
arreglo_frutas = np.array([
    ['Pina', 'Manzana', 'Pera', 'Melon'], 
    ['Pera', 'Uva', 'Naranja','Papaya'],
    ['Frutilla', 'Platano', 'Granadilla', 'Sandia']])

In [9]:
arreglo_frutas.shape

(3, 4)

In [11]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [12]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2],
])

In [13]:
arreglo_filas

array([[0, 0],
       [1, 1],
       [2, 2]])

In [15]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Granadilla']], dtype='<U10')

In [16]:
arreglo_frutas

array([['Pina', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [42]:
arr_indice_fil = np.array([
    [0,0],
    [1,1],
    [2,2]
])
arr_indice_fil.shape

(3, 2)

In [19]:
arr_col = np.array([
    [2,3],
    [2,3],
    [2,3],
])

In [20]:
arreglo_frutas[arr_indice_fil,arr_col]

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Granadilla', 'Sandia']], dtype='<U10')

In [31]:
arreglo_frutas2 = np.array([[
    ['Pina', 'Manzana', 'Pera', 'Melon'], 
    ['Pera', 'Uva', 'Naranja','Papaya'],
    ['Frutilla', 'Platano', 'Granadilla', 'Sandia']],
    [['tomate', 'berenjena', 'aguacate', 'limon'], 
    ['tamarindo', 'azafran', 'maracuya','naranjilla'],
    ['manzana2', 'Platano2', 'Granadilla2', 'Sandia2']]])

In [32]:
arreglo_frutas2.reshape(4,3,2)


array([[['Pina', 'Manzana'],
        ['Pera', 'Melon'],
        ['Pera', 'Uva']],

       [['Naranja', 'Papaya'],
        ['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia']],

       [['tomate', 'berenjena'],
        ['aguacate', 'limon'],
        ['tamarindo', 'azafran']],

       [['maracuya', 'naranjilla'],
        ['manzana2', 'Platano2'],
        ['Granadilla2', 'Sandia2']]], dtype='<U11')

In [45]:
arr_fil_fru= np.array([
    [[0,0],
    [],
    
    [[0,0,1],
    [1,1,1]
   ]])

    


In [48]:
arr_fil_fru.reshape(3,2,2)

array([[[0, 0],
        [0, 1]],

       [[1, 0],
        [0, 0]],

       [[1, 1],
        [1, 1]]])

In [57]:
arreglo_frutas2[np.array([1,1,0]),np.array([1,1,1]),np.array([1,1,2])]

array(['azafran', 'azafran', 'Naranja'], dtype='<U11')

In [71]:
bandera=arreglo_frutas[0,0].startswith('P')

In [72]:
if(bandera==True):
    print(arreglo_frutas[i,j])

IndentationError: unexpected indent (<ipython-input-72-ce06cd208ddc>, line 3)