In [1]:
import numpy as np

In [2]:
angulos_cero_noventa = np.array((0,30,45,60,90))

In [3]:
np.pi

3.141592653589793

In [7]:
angulos_radianes = angulos_cero_noventa *np.pi/180

In [8]:
angulos_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [9]:
np.sin(angulos_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [10]:
np.cos(angulos_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [14]:
#arreglos randomicos
arreglos_random = np.random.rand(10)

In [15]:
arreglos_random

array([0.09374169, 0.39003253, 0.75033295, 0.88755261, 0.42181042,
       0.67170321, 0.45565897, 0.40035642, 0.32048058, 0.21149515])

In [16]:
np.random.randint(10)

6

In [17]:
#Desviacion Estandar
npc.std(arreglo_random_diez)

NameError: name 'npc' is not defined