In [3]:
import numpy as np
array = np.arange(0,10)

In [4]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array[0:5:1]

array([0, 1, 2, 3, 4])

In [17]:
a = np.arange(1,10)

In [18]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
np.argwhere( a!=0 )

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 6],
       [10],
       [11],
       [12],
       [13],
       [14]], dtype=int64)

In [23]:
a.flatten

<function ndarray.flatten>