In [3]:
###1
import numpy as np
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
###2
a[5]= 0
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [14]:
###3
b = np.arange(0,50)
b
b[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [17]:
###4
c= np.arange(0,9)
c.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
###5 
arreglo = np.array([1,2,0,0,4,0])
np.argwhere( arreglo!=0 )

array([[0],
       [1],
       [4]], dtype=int64)

In [24]:
###6
d= np.array([1,0,0,0,1,0,0,0,1])
d.reshape(3,3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
###7
e = np.random.random((3,3,3))
e


array([[[0.66612173, 0.79540673, 0.01310052],
        [0.01823544, 0.57655353, 0.2555798 ],
        [0.50570255, 0.08567605, 0.78258869]],

       [[0.96162116, 0.01021152, 0.83939248],
        [0.92659117, 0.7401946 , 0.67407801],
        [0.05840727, 0.60660863, 0.30326499]],

       [[0.21847347, 0.92248386, 0.43116383],
        [0.16693013, 0.77188712, 0.0014267 ],
        [0.65197818, 0.87436888, 0.64924531]]])

In [34]:
###8
f = np.random.random((10,10))
print(f)
print(  f.argmax() )
print( f.ravel()[r.argmax()] )

print(np.unravel_index(f.argmax(), f.shape))
f[np.unravel_index(f.argmax(), f.shape)]


[[0.14368896 0.37018595 0.80771964 0.85408824 0.90188192 0.22822667
  0.21201315 0.27475647 0.55885827 0.30049248]
 [0.7455117  0.3643458  0.02313062 0.96611396 0.62686664 0.25488116
  0.39914753 0.63672484 0.03171171 0.9913187 ]
 [0.37359177 0.30962168 0.43186093 0.40466431 0.36036096 0.41223521
  0.43217763 0.44052894 0.85334759 0.46895664]
 [0.61839473 0.00277318 0.99519552 0.87415489 0.48147547 0.4996624
  0.09536083 0.51735959 0.96505053 0.33959191]
 [0.49301676 0.94782738 0.628784   0.67848929 0.8830825  0.20772066
  0.28034024 0.73491347 0.16361405 0.26068314]
 [0.70031631 0.45236265 0.91126527 0.26521021 0.35850785 0.60722611
  0.56186979 0.45160415 0.24443914 0.71827522]
 [0.06197618 0.42680723 0.67519212 0.74887821 0.59095931 0.98530322
  0.08319896 0.21163272 0.15514441 0.06201976]
 [0.03420662 0.40778906 0.87749832 0.081571   0.76374111 0.79205803
  0.21535247 0.48255413 0.10753251 0.31624168]
 [0.20785471 0.47695591 0.47365376 0.74142261 0.87028343 0.32285025
  0.51056041 

0.995195519677902

In [ ]:
###9

In [ ]:
###10