In [ ]:
###

In [2]:
import numpy as np

In [37]:
###Crear un arreglo del 0 al 9
arreglo_num = np.arange(10)

In [33]:
arreglo_num


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
### Elevar todo el arreglo al cuadrado
arreglo_num**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [39]:
### Del arreglo generar  una matriz 2*5
arr_2=arreglo_num.reshape(2,5)

In [20]:
arr_2.shape

(2, 5)

In [40]:
### Regresar el arreglo a su forma original sin usar reshape
arr_2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
### Generar dos arreglos del mismo tamaño apartir del arreglo orginal
arr_3,arr_4=np.split(arreglo_num,2)

In [24]:
arr_3

array([0, 1, 2, 3, 4])

In [25]:
arr_4

array([5, 6, 7, 8, 9])

In [32]:
arr_5= arreglo_num.reshape(5,2)

In [34]:
arr_5


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
### Generar la transpuesta
arr_5t=arr_5.T

In [36]:
arr_5t

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])